name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint
      - run: npm run test

      # example project
      - run: npm pack
      - run: npm ci
        working-directory: example
      - run: npm install --no-save ../henrist-cdk-cloudfront-auth-0.0.0-development.tgz
        working-directory: example
      - run: npm run test
        working-directory: example

      - run: npm run semantic-release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
